# Generated by Django 5.2.4 on 2025-08-08 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Género')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Plataforma')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Juego')),
                ('descripcion', models.TextField(verbose_name='Descripción Completa')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('desarrollador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Desarrollador')),
                ('editor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Editor')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='juegos/portadas/', verbose_name='Imagen de Portada')),
                ('video_trailer_url', models.URLField(blank=True, null=True, verbose_name='URL del Trailer')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('promedio_puntuacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Puntuación Promedio')),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('generos', models.ManyToManyField(related_name='juegos', to='games.genero', verbose_name='Géneros')),
                ('plataformas', models.ManyToManyField(related_name='juegos', to='games.plataforma', verbose_name='Plataformas')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado para Publicación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='games.juego', verbose_name='Juego')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'games_comentariojuego',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Valor de la Puntuación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.juego', verbose_name='Juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Puntuación',
                'verbose_name_plural': 'Puntuaciones',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('juego', 'usuario')},
            },
        ),
    ]
