# Generated by Django 5.2.4 on 2025-07-31 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='juego',
            name='agregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por'),
        ),
        migrations.AddField(
            model_name='juego',
            name='generos',
            field=models.ManyToManyField(related_name='juegos', to='games.genero', verbose_name='Géneros'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.juego', verbose_name='Juego'),
        ),
        migrations.AddField(
            model_name='juego',
            name='plataformas',
            field=models.ManyToManyField(related_name='juegos', to='games.plataforma', verbose_name='Plataformas'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.juego', verbose_name='Juego'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='puntuacion',
            unique_together={('juego', 'usuario')},
        ),
    ]
