# Generated by Django 5.2.4 on 2025-08-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariojuego',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('aprobar_comentario', 'Puede aprobar comentarios')], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
