# Generated by Django 5.2.4 on 2025-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Artículo')),
                ('subtitulo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_blog',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Blog',
                'verbose_name_plural': 'Categorías de Blog',
                'ordering': ['nombre'],
            },
        ),
    ]
