# Generated by Django 5.2.4 on 2025-08-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen_principal',
        ),
    ]
