# Generated by Django 5.2.4 on 2025-08-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarioarticulo',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('aprobar_comentario', 'Puede aprobar comentarios')], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AddField(
            model_name='comentarioarticulo',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='blog/imagenes', verbose_name='Imagen Principal (Archivo)'),
        ),
    ]
