# Generated by Django 5.2.4 on 2025-08-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articulo_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagen Principal (Archivo)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen Principal (URL)'),
        ),
    ]
