# Generated by Django 5.2.4 on 2025-08-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('blog', '0003_articulo_imagen_principal_articulo_imagen_url'),
    ]

    operations = [
    ]
