# Generated by Django 5.2.4 on 2025-08-12 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined', '-nombre'), 'permissions': [('es_colaborador', 'Puede editar y crear contenido'), ('puede_eliminar_usuario', 'Puede eliminar usuarios no superusuarios')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='es_colaborador',
            field=models.BooleanField(default=False, verbose_name='es colaborador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='fecha nacimiento'),
        ),
    ]
