# Generated by Django 5.2.4 on 2025-08-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-nombre',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='correo',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='tu_correo@example.com', max_length=254, unique=True),
        ),
    ]
