# Generated by Django 5.2.4 on 2025-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, default='usuario/user-default.jpg', null=True, upload_to='usuario'),
        ),
    ]
